use anyhow::{Context, Result};
use async_trait::async_trait;
use chrono::{DateTime, Utc};
use serde::Deserialize;
use std::time::Duration;
use tonic::transport::{Certificate, Channel, ClientTlsConfig, Endpoint, Identity};

use crate::config::Config;
use crate::connectors::{Connector, HealthStatus};
use crate::models::alert::{AlertStatus, NormalizedAlert};

pub mod api {
    tonic::include_proto!("proto");
}
use crate::models::alert::Severity;
use api::api_client::ApiClient;
use api::{VqlCollectorArgs, VqlRequest};
use uuid::Uuid;

/// Represents the `api_client.yaml` configuration generated by Velociraptor.
#[derive(Debug, Deserialize)]
struct VelociraptorClientConfig {
    api_connection_string: String,
    client_cert: String,
    client_private_key: String,
    ca_certificate: String,
}

pub struct VelociraptorConnector {
    channel: Channel,
}

impl VelociraptorConnector {
    pub async fn new(config: &Config) -> Result<Self> {
        let yaml_content = std::fs::read_to_string(&config.velociraptor_api_client_yaml)
            .context("Failed to read Velociraptor api_client.yaml")?;

        let vr_config: VelociraptorClientConfig = serde_yaml::from_str(&yaml_content)
            .context("Failed to parse Velociraptor api_client.yaml")?;

        let ca_cert = Certificate::from_pem(&vr_config.ca_certificate);
        let identity = Identity::from_pem(&vr_config.client_cert, &vr_config.client_private_key);

        let tls = ClientTlsConfig::new()
            .ca_certificate(ca_cert)
            .identity(identity)
            .domain_name("VelociraptorServer"); // Standard SAN used by Velociraptor

        let endpoint_url = format!("https://{}", vr_config.api_connection_string);
        let endpoint = Endpoint::from_shared(endpoint_url)?
            .tls_config(tls)?
            .connect_timeout(Duration::from_secs(5))
            .timeout(Duration::from_secs(10));

        let channel = endpoint.connect_lazy();

        Ok(Self { channel })
    }

    async fn run_query(&self, query: &str) -> Result<Vec<serde_json::Value>> {
        let mut client = ApiClient::new(self.channel.clone());

        let vql_query = VqlRequest {
            name: "query".to_string(),
            vql: query.to_string(),
        };

        let args = VqlCollectorArgs {
            env: vec![],
            query: vec![vql_query],
            max_wait: 10,
            max_row: 500,
            ops_per_second: 0.0,
            org_id: String::new(),
            timeout: 0,
        };

        let mut request = tonic::Request::new(args);
        request.set_timeout(Duration::from_secs(30));
        let mut stream = client.query(request).await?.into_inner();

        let mut all_rows = Vec::new();

        while let Some(response) = stream.message().await? {
            if !response.response.is_empty() {
                // response.response is a JSON string of rows
                let parsed: Vec<serde_json::Value> = serde_json::from_str(&response.response)?;
                all_rows.extend(parsed);
            }
        }

        Ok(all_rows)
    }
}

#[async_trait]
impl Connector for VelociraptorConnector {
    fn id(&self) -> &'static str {
        "velociraptor"
    }

    async fn health_check(&self) -> HealthStatus {
        match self.run_query("SELECT * FROM info()").await {
            Ok(_) => HealthStatus::Healthy,
            Err(e) => HealthStatus::Down {
                reason: e.to_string(),
            },
        }
    }

    async fn fetch_alerts(&self, since: DateTime<Utc>) -> Result<Vec<NormalizedAlert>> {
        let vql = format!(
            "SELECT * FROM Artifact.Custom.Server.Alerts(Since='{}')",
            since.to_rfc3339()
        );
        let rows = self.run_query(&vql).await?;

        let mut alerts = Vec::new();
        for row in rows {
            let id_str = row.get("id").and_then(|v| v.as_str()).unwrap_or("");

            let id = Uuid::parse_str(id_str).unwrap_or_else(|_| Uuid::new_v4());

            let severity_str = row
                .get("severity")
                .and_then(|v| v.as_str())
                .unwrap_or("Medium");

            let severity = match severity_str.to_lowercase().as_str() {
                "high" => Severity::High,
                "critical" => Severity::Critical,
                "low" => Severity::Low,
                _ => Severity::Medium,
            };

            let source = row
                .get("source")
                .and_then(|v| v.as_str())
                .unwrap_or("velociraptor")
                .to_string();

            let timestamp = row
                .get("timestamp")
                .and_then(|v| v.as_str())
                .and_then(|v| DateTime::parse_from_rfc3339(v).ok())
                .map(|v| v.with_timezone(&Utc))
                .unwrap_or_else(Utc::now);

            alerts.push(NormalizedAlert {
                id,
                connector_id: self.id().to_string(),
                severity,
                source,
                timestamp,
                raw_payload: row,
                status: AlertStatus::Open,
            });
        }

        Ok(alerts)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;
    use serde_json::json;

    #[test]
    fn test_alert_mapping() {
        let ts = Utc.with_ymd_and_hms(2023, 1, 1, 12, 0, 0).unwrap();
        let ts_str = ts.to_rfc3339();

        let row = json!({
            "id": "123e4567-e89b-12d3-a456-426614174000",
            "severity": "Critical",
            "source": "test_source",
            "timestamp": ts_str,
            "description": "Test alert"
        });

        // We can test the parsing logic directly, but since fetch_alerts needs a client,
        // let's extract the parsing logic to a separate function or test it here manually based on the same logic.
        let id_str = row.get("id").and_then(|v| v.as_str()).unwrap_or("");
        let id = Uuid::parse_str(id_str).unwrap_or_else(|_| Uuid::new_v4());
        assert_eq!(id.to_string(), "123e4567-e89b-12d3-a456-426614174000");

        let severity_str = row
            .get("severity")
            .and_then(|v| v.as_str())
            .unwrap_or("Medium");
        let severity = match severity_str.to_lowercase().as_str() {
            "high" => Severity::High,
            "critical" => Severity::Critical,
            "low" => Severity::Low,
            _ => Severity::Medium,
        };
        assert_eq!(severity, Severity::Critical);

        let timestamp = row
            .get("timestamp")
            .and_then(|v| v.as_str())
            .and_then(|v| DateTime::parse_from_rfc3339(v).ok())
            .map(|v| v.with_timezone(&Utc))
            .unwrap_or_else(Utc::now);
        assert_eq!(timestamp, ts);
    }
}
