//! `NormalizedAlert` — the canonical alert representation used throughout
//! Shieldgrid Core.
//!
//! Every connector maps its native alert format into this struct, so the rest
//! of the platform (API routes, case management, frontend) never needs to know
//! anything about the source tool's data shape.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ── Severity ─────────────────────────────────────────────────────────────────

/// Normalised severity level for an alert.
///
/// Connectors map their native severity scale (e.g. Wazuh rule levels 1–15)
/// into one of these five buckets.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    /// Informational — no immediate action required.
    Info,
    /// Low severity — worth noting but unlikely to require urgent response.
    Low,
    /// Medium severity — investigate in a timely manner.
    Medium,
    /// High severity — investigate promptly; likely a real incident.
    High,
    /// Critical severity — immediate response required.
    Critical,
}

// ── AlertStatus ──────────────────────────────────────────────────────────────

/// Lifecycle state of a normalised alert within Shieldgrid.
///
/// Transitions (Open → Acknowledged → Closed) will be driven by the case
/// management layer introduced in Phase 1.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AlertStatus {
    /// Newly ingested; no analyst has acted on it yet.
    Open,
    /// An analyst has acknowledged the alert and is investigating.
    Acknowledged,
    /// Investigation complete; alert is resolved or dismissed.
    Closed,
}

// ── NormalizedAlert ───────────────────────────────────────────────────────────

/// A connector-agnostic alert, produced by mapping each source tool's native
/// format into this common schema.
///
/// # Field documentation
///
/// | Field | Description |
/// |---|---|
/// | `id` | Unique identifier generated by Shieldgrid at ingestion time. |
/// | `connector_id` | ID of the connector that produced this alert (e.g. `"wazuh"`). |
/// | `severity` | Normalised severity bucket. |
/// | `source` | Human-readable origin within the connector (e.g. agent hostname). |
/// | `timestamp` | Original event timestamp from the source tool, in UTC. |
/// | `raw_payload` | Complete raw alert JSON from the source, preserved for audit. |
/// | `status` | Current lifecycle state of the alert within Shieldgrid. |
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NormalizedAlert {
    /// Unique identifier generated by Shieldgrid at ingestion time.
    pub id: Uuid,

    /// ID of the connector that produced this alert (e.g. `"wazuh"`).
    pub connector_id: String,

    /// Normalised severity bucket.
    pub severity: Severity,

    /// Human-readable origin within the connector (e.g. agent hostname,
    /// IP address, or device name).
    pub source: String,

    /// Original event timestamp from the source tool, in UTC.
    pub timestamp: DateTime<Utc>,

    /// Complete raw alert JSON from the source, preserved for audit and
    /// future re-parsing without data loss.
    pub raw_payload: serde_json::Value,

    /// Current lifecycle state of the alert within Shieldgrid.
    pub status: AlertStatus,
}
